version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - database_env
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT-5432}:5432
